# Generated by Django 4.0 on 2021-12-08 18:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Hiring", "Hiring"),
                            ("Hiring_Freeze", "Hiring Freeze"),
                            ("Stable", "Stable"),
                            ("Contract", "Contract"),
                        ],
                        default="Stable",
                        max_length=20,
                    ),
                ),
                ("updated", models.DateTimeField(default=django.utils.timezone.now)),
                ("notest", models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
