# Generated by Django 4.0 on 2021-12-12 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_alter_company_notest_alter_company_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="status",
            field=models.CharField(
                choices=[
                    ("Hiring", "Hiring"),
                    ("Hiring_Freeze", "Hiring Freeze"),
                    ("Stable", "Stable"),
                    ("Contract", "Contract"),
                ],
                default="Stable",
                max_length=20,
            ),
        ),
    ]
