# Generated by Django 4.0 on 2021-12-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_alter_company_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_from', models.EmailField(max_length=254)),
                ('e_to', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=250)),
            ],
        ),
    ]
